# SYSC 4415 Assignment 3

Group members:
*   Johnny Mack
*   Zirui Qiao
*   Matthew Siu

# Project setup
Download and unzip A3 dataset.

In [ ]:
# Download dataset
! rm -rf SYSC4415W23_A3_dataset SYSC4415W23_A3_dataset.zip
! wget https://github.com/jrgreen7/SYSC4906/releases/download/Assignment3/SYSC4415W23_A3_dataset.zip && unzip SYSC4415W23_A3_dataset.zip

--2023-04-07 20:18:14--  https://github.com/jrgreen7/SYSC4906/releases/download/Assignment3/SYSC4415W23_A3_dataset.zip
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/210406387/65aaa87c-b1e0-476c-bb66-242944754062?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20230407%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230407T201814Z&X-Amz-Expires=300&X-Amz-Signature=ae75eed3bc1650573f324a9f1492afdbad650b91ee2987c6fff9e9e836034484&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=210406387&response-content-disposition=attachment%3B%20filename%3DSYSC4415W23_A3_dataset.zip&response-content-type=application%2Foctet-stream [following]
--2023-04-07 20:18:14--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/210406387/65aaa87c-b1e0-476

# Prepare datasets

1.   Load datasets (train/val and test).
2.   Data preprocessing (e.g., imputation).

## Load datasets

In [ ]:
# Imports
from pandas import read_csv

In [ ]:
# Load train/val extracted_features and labels datasets
train_val_features = read_csv('SYSC4415W23_A3_dataset/train/extracted_features.csv')
train_val_labels = read_csv('SYSC4415W23_A3_dataset/train/labels.csv')

# Load test extracted_features and labels datasets
test_features = read_csv('SYSC4415W23_A3_dataset/test/extracted_features.csv')
test_labels = read_csv('SYSC4415W23_A3_dataset/test/labels.csv')

# Utility dictionary for mapping sample_id to their labels
sample_id_to_label = dict([(row.sample_id, row.label) for row in train_val_labels.itertuples()])

## Impute train/val dataset

In [ ]:
# Imports
from sklearn.impute import SimpleImputer

In [ ]:
# Impute train/val and test data from extracted_features.csv
imputer = SimpleImputer(strategy='mean')
train_val_features = imputer.fit_transform(train_val_features)
test_features = imputer.fit_transform(test_features)

# Prepare models


1.   Select models.
2.   Tune model hyperparameters.
3.   Create and train models with optimal hyperparameters.


## Select models

In [ ]:
# Imports
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier

## Tune hyperparameters

In [ ]:
# Imports
from numpy.random import rand
from numpy import array
import time
from sklearn.metrics import accuracy_score

In [ ]:
# Split train/val dataset into a random train/val split (used to generate 30_predictions.csv)
VAL_SIZE = 0.1
msk = rand(len(train_val_features)) > VAL_SIZE
train_features = train_val_features[msk]
val_features = train_val_features[~msk]
print(train_features.shape)
print(val_features.shape)

# Get labels based on the first columns (sample_id)
train_labels = array([sample_id_to_label[sample_id] for sample_id in train_features[:, 0].astype(int)])
val_labels = array([sample_id_to_label[sample_id] for sample_id in val_features[:, 0].astype(int)])

(1446, 7039)
(175, 7039)


In [ ]:
 '''
Optimize model 1 max_depth hyperparameter.

L: 1, Accuracy: 0.7126436781609196, Time: 609.077497959137
L: 2, Accuracy: 0.735632183908046, Time: 1180.0929119586945
L: 3, Accuracy: 0.7528735632183908, Time: 1751.6518223285675

opt_depth = 0
opt_acc_score = 0

for L in range (1, 4):
  model1_tuning = GradientBoostingClassifier(max_depth=L)

  # Train model
  start_time = time.time()
  model1_tuning.fit(train_features[:, 1:], train_labels)
  train_time = time.time() - start_time

  # Calculate model accuracy
  y_pred = model1_tuning.predict(val_features[:, 1:])
  acc_score = accuracy_score(val_labels, y_pred)
  print(f'L: {L}, Accuracy: {acc_score}, Time: {train_time}')

  # Update opt L
  if(acc_score > opt_acc_score):
    opt_depth = L
    opt_acc_score = acc_score
    print(f'New optimal L: {L}')

print(f'Optimal L: {opt_depth}')
'''
# Optimal depth is 3

"\nOptimize model 1 max_depth hyperparameter.\n\nL: 1, Accuracy: 0.7126436781609196, Time: 609.077497959137\nL: 2, Accuracy: 0.735632183908046, Time: 1180.0929119586945\nL: 3, Accuracy: 0.7528735632183908, Time: 1751.6518223285675\n\nopt_depth = 0\nopt_acc_score = 0\n\nfor L in range (1, 4):\n model1_tuning = GradientBoostingClassifier(max_depth=L)\n\n # Train model\n start_time = time.time()\n model1_tuning.fit(train_features[:, 1:], train_labels)\n train_time = time.time() - start_time\n\n # Calculate model accuracy\n y_pred = model1_tuning.predict(val_features[:, 1:])\n acc_score = accuracy_score(val_labels, y_pred)\n print(f'L: {L}, Accuracy: {acc_score}, Time: {train_time}')\n\n # Update opt L\n if(acc_score > opt_acc_score):\n   opt_depth = L\n   opt_acc_score = acc_score\n   print(f'New optimal L: {L}')\n\nprint(f'Optimal L: {opt_depth}')\n"

In [ ]:
# Tuning hyperparameter (max_depth) for Model 2
'''
from xgboost import XGBClassifier

OptimalL = 0
bestAccuracyScore = 0

for L in range (1, 10):

  start_time = time.time()

  # Train model
  model2_tuning = XGBClassifier(max_depth=L)
  model2_tuning.fit(train_features[:, 1:], train_labels)

  y_pred = model2_tuning.predict(val_features[:, 1:])
  # calculate accuracy
  accuracy = accuracy_score(val_features[:, 0], y_pred)
  train_time = time.time() - start_time
  print(L)
  print(f"\nAccuracy: {accuracy}, Time: {train_time}")
  if(accuracy > bestAccuracyScore):
    print("New best L")
    bestAccuracyScore = accuracy
    OptimalL = L

  print(OptimalL)

  # The optimal depth was determined to be 6
'''

'\nfrom xgboost import XGBClassifier\n\nOptimalL = 0\nbestAccuracyScore = 0\n\nfor L in range (1, 10):\n\n  start_time = time.time()\n\n  # Train model\n  model2_tuning = XGBClassifier(max_depth=L)\n  model2_tuning.fit(train_features[:, 1:], train_labels)\n\n  y_pred = model2_tuning.predict(val_features[:, 1:])\n  # calculate accuracy\n  accuracy = accuracy_score(val_features[:, 0], y_pred)\n  train_time = time.time() - start_time\n  print(L)\n  print(f"\nAccuracy: {accuracy}, Time: {train_time}")\n  if(accuracy > bestAccuracyScore):\n    print("New best L")\n    bestAccuracyScore = accuracy\n    OptimalL = L\n  \n  print(OptimalL)\n\n  # The optimal depth was determined to be 6\n'

## Create and train models with optimal hyperparameters

In [ ]:
# Create 3 different models (we will combine their predictions later)

# Model 1: GradientBoosting
model1 = GradientBoostingClassifier(max_depth=3)

# Model 2: XGBoost
model2 = XGBClassifier(max_depth=6)

# Model 3: RandomForest
model3 = RandomForestClassifier(n_estimators=170, class_weight='balanced_subsample', max_depth=16, min_samples_split=2, random_state=42)

# Store models in an array to facilitate training
models = [model1, model2, model3]

In [ ]:
# Train optimal models and calculate their accuracies
for model in models:

  # Train model
  start_time = time.time()
  model.fit(train_features[:, 1:], train_labels)
  train_time = time.time() - start_time
  print(f'{model} training completed')
  print(f'Train time: {train_time}')

  # Calculate model accuracy
  y_pred = model.predict(val_features[:, 1:])
  model_acc_score = accuracy_score(val_labels, y_pred)
  print(f'Accuracy: {model_acc_score}\n')

# Generate predictions for test dataset

**Class Labels**
* Index for slow/normal walk: 0
* Index for fast walk: 1
* Index for stair ascent: 2
* Index for stair descent: 3
* Index for jumping jacks: 4

**Steps**
1.   Generate predictions from each invididual model.
2.   Merge predictions using Majority Voting.
3.   Write majority vote predictions to 30_predictions.csv.



## Get individual model predictions

In [ ]:
# Generate individual model predictions
predictions = {}   # {sample_id: [labels]} Store model predictions for Majority Vote

for model in models:
  # Iterate through each test sample
  for i in range(len(test_features)):
    y_pred = model.predict([test_features[i, 1:]]) # Predict using all columns except sample_id
    y_pred = y_pred[0].astype(int)
    sample_id = test_features[i, 0].astype(int)    # Column 0 of test data is the sample_id
    if sample_id not in predictions:
      predictions[sample_id] = []
    predictions[sample_id].append(y_pred)          # Add prediction to dictionary

# Print predictions dictionary
for k, v in predictions.items():
  print(f'{k}: [{v[0]}, {v[1]}, {v[2]}]')

# Merge predictions using Majority Voting

In [ ]:
# Imports
from pandas import read_csv
from collections import Counter
from random import randint

In [ ]:
# Collect the sample IDs in the same order they appear in labels.csv in the test folder
LABELS_CSV_PATH = 'SYSC4415W23_A3_dataset/test/labels.csv'
labels_csv_df = read_csv(LABELS_CSV_PATH, index_col=False)
csv_sample_ids = labels_csv_df['sample_id']
print(f'csv_sample_ids: {csv_sample_ids.tolist()}')

# Construct Majority Vote predictions to be written to 30_predictions.csv
majority_votes = []
print('Predictions => Majority Vote:')

# Condense each array of predictions to a single prediction based on Majority Vote
# If there's a tie, randomly pick one of the predictions
for sample_id in csv_sample_ids:
  counts = Counter(predictions[sample_id])

  # Maximum number of models predicting the same label
  max_count = max(counts.values())

  # Gather all predictions that match max_count
  y_preds = [y_pred for y_pred, count in counts.items() if count == max_count]

  # Produce a single prediction based on all predictions that matched max_count
  if len(y_preds) == 1: y_pred = y_preds[0]             # Majority Vote
  else: y_pred = y_preds[randint(0, len(y_preds) - 1)]  # Random prediction
  majority_votes.append(y_pred)
  print(f'{predictions[sample_id]} => {y_pred} (sample {sample_id})')

## Write majority vote predictions to 30_predictions.csv

In [ ]:
# Imports
from pandas import DataFrame

In [ ]:
# Combine sample_id and label columns into a DataFrame
labels_csv_df['label'] = majority_votes
print(labels_csv_df)

# Write predictions to 30_predictions.csv in root folder
PREDICTIONS_PATH = './30_predictions.csv'
labels_csv_df.to_csv(PREDICTIONS_PATH, encoding='utf-8', index=False)

# Train models and validate performance on combined model using cross-validation


1.   Split train/val dataset into k folds.
2.   Calculate k accuracy scores using cross-validation on the combined model.
3.   Calculate mean and standard deviation of the combined model's accuracy scores.
4.   Write results to 30_predicted_performance.csv.


## Split trian/val dataset into k folds

In [ ]:
# Imports
from numpy import split
import time
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from numpy import concatenate
from collections import Counter
from random import randint
from sklearn.metrics import accuracy_score

In [ ]:
# Split train/val data into k folds
NUM_FOLDS = 3
k_folds = split(train_val_features[:-1], NUM_FOLDS)
for fold in k_folds:
  print(fold.shape)

## Calculate accuracy scores using cross-validation on the combined model

In [ ]:
# Store accuracies from combined model to calculcate mean and std dev
combined_accuracies = []
collected_majority_vote = []
collected_actual_label = []

for i in range(NUM_FOLDS):
  # Set train/val datasets for the current iteration
  training_folds = [fold for idx,fold in enumerate(k_folds) if idx!=i]
  training_set = concatenate(training_folds)
  training_labels = [sample_id_to_label[sample_id] for sample_id in training_set[:, 0].astype(int)]
  validation_set = k_folds[i]
  validation_labels = [sample_id_to_label[sample_id] for sample_id in validation_set[:, 0].astype(int)]

  # Initialize 3 different models to be trained for the current iteration
  model1 = GradientBoostingClassifier(max_depth=3)
  model2 = XGBClassifier(max_depth=6)
  model3 = RandomForestClassifier(n_estimators=170, class_weight='balanced_subsample', max_depth=16, min_samples_split=2, random_state=42)
  models = [model1, model2, model3]

  # Train the models
  for model in models:
    start_time = time.time()
    model.fit(training_set[:, 1:], training_labels)
    train_time = time.time() - start_time
    print(f'{model} training completed in {train_time} secs')

  predictions = {}   # {sample_id: [labels]} Store model predictions for Majority Vote

  # Make predictions from each model
  for model in models:
    for j in range(len(validation_set)):
      y_pred = model.predict([validation_set[j, 1:]])[0].astype(int)
      sample_id = validation_set[j, 0].astype(int)
      if sample_id not in predictions:
        predictions[sample_id] = []
      predictions[sample_id].append(y_pred)

  majority_votes = []   # Construct Majority Vote predictions (combined model)

  # Condense each array of predictions to a single prediction based on Majority Vote
  # If there's a tie, randomly pick one of the predictions
  for sample_id in predictions.keys():
    counts = Counter(predictions[sample_id])

    # Maximum number of models predicting the same label
    max_count = max(counts.values())

    # Gather all predictions that match max_count
    y_preds = [y_pred for y_pred, count in counts.items() if count == max_count]

    # Produce a single prediction based on all predictions that matched max_count
    if len(y_preds) == 1: y_pred = y_preds[0]             # Majority Vote
    else: y_pred = y_preds[randint(0, len(y_preds) - 1)]  # Random prediction
    majority_votes.append(y_pred)

  collected_majority_vote.append(majority_votes)
  collected_actual_label.append(validation_labels)
  combined_accuracy = accuracy_score(majority_votes, validation_labels)
  combined_accuracies.append(combined_accuracy)
  print(f'Fold {i} => Combined accuracy: {combined_accuracy}')

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import PrecisionRecallDisplay
import matplotlib.pyplot as plt
import numpy as np

pred_dict = {'slow_walk':[], 'fast_walk':[], 'stair_ascent':[], 'stair_descent':[], 'jumping_jacks':[]}
true_dict = {'slow_walk':[], 'fast_walk':[], 'stair_ascent':[], 'stair_descent':[], 'jumping_jacks':[]}

total_temp_pred = []
total_temp_actual = []

# combine 3 iterations and prepare PR dataset
for i in range(len(collected_majority_vote)):
  counter = 0
  temp_pred = np.array(collected_majority_vote[i])
  temp_true = np.array(collected_actual_label[i])
  total_temp_pred = np.concatenate((total_temp_pred, collected_majority_vote[i]))
  total_temp_actual = np.concatenate((total_temp_actual, collected_actual_label[i]))
  for key in pred_dict:
      pred_dict[key] = np.concatenate((pred_dict[key], np.where(temp_pred == counter, 1, 0)))
      true_dict[key] = np.concatenate((true_dict[key], np.where(temp_true == counter, 1, 0)))
      counter += 1

# draw confusion matrix
conf_mat = confusion_matrix(total_temp_actual, total_temp_pred, labels=[0, 1, 2, 3, 4])
print(f"Confusion Matrix:")
print(conf_mat)

# draw PR curves
fig, axs = plt.subplots(1, 5, figsize=(20, 3.5))
counter = 0
for key in pred_dict:
  PrecisionRecallDisplay.from_predictions(y_true=true_dict[key], y_pred=pred_dict[key], name=key, ax=axs[counter])
  axs[counter].set_title(key + " PR curve")
  counter += 1

fig.tight_layout()
plt.show()

Confusion Matrix:
[[3 0 0 0 0]
 [0 3 0 0 0]
 [0 0 3 0 0]
 [0 0 0 2 2]
 [0 0 0 1 1]]


## Calculate mean and std dev of the combined model's accuracy

In [ ]:
# Imports
from statistics import mean, stdev

In [ ]:
# Calculate the average accuracy over k folds
predicted_accuracy = mean(combined_accuracies)
print(f'Predicted accuracy on test data: {predicted_accuracy}')

# Calculate the standard deviation of the accuracies over k folds
predicted_accuracy_std = stdev(combined_accuracies)
print(f'Predicted standard deviation of accuracy on test data: {predicted_accuracy_std}')

## Write to 30_predicted_performance.csv

In [ ]:
# Imports
from pandas import DataFrame

In [ ]:
# Prepare DataFrame
predicted_performance_df = DataFrame({'predicted_accuracy': [predicted_accuracy],
                                      'predicted_accuracy_std': [predicted_accuracy_std]})

# Write predicted accuracy and its standard deviation to 30_predicted_performace.csv in root folder
PREDICTED_PERFORMANCE_PATH = './30_predicted_performance.csv'
predicted_performance_df.to_csv(PREDICTED_PERFORMANCE_PATH, encoding='utf-8', index=False)

In [ ]:
# Download 30_predictions.csv and 30_predicted_performance.csv in case the runtime disconnects
from google.colab import files
files.download(PREDICTIONS_PATH)
files.download(PREDICTED_PERFORMANCE_PATH)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>